name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  ci-checks:
    runs-on: ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm add turbo --global

      - name: Run checks for all packages
        env:
          NPM_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_NPM_TOKEN }}
        run: |
          pnpm --parallel -r postinstall
          pnpm -r nuxt typecheck
